export const countries = [
  { label: 'Andorra' },
  { label: 'United Arab Emirates' },
  { label: 'Afghanistan' },
  { label: 'Antigua and Barbuda' },
  { label: 'Anguilla' },
  { label: 'Albania' },
  { label: 'Armenia' },
  { label: 'Angola' },
  { label: 'Antarctica' },
  { label: 'Argentina' },
  { label: 'American Samoa' },
  { label: 'Austria' },
  { label: 'Australia' },
  { label: 'Aruba' },
  { label: 'Alland Islands' },
  { label: 'Azerbaijan' },
  { label: 'Bosnia and Herzegovina' },
  { label: 'Barbados' },
  { label: 'Bangladesh' },
  { label: 'Belgium' },
  { label: 'Burkina Faso' },
  { label: 'Bulgaria' },
  { label: 'Bahrain' },
  { label: 'Burundi' },
  { label: 'Benin' },
  { label: 'Saint Barthelemy' },
  { label: 'Bermuda' },
  { label: 'Brunei Darussalam' },
  { label: 'Bolivia' },
  { label: 'Brazil' },
  { label: 'Bahamas' },
  { label: 'Bhutan' },
  { label: 'Bouvet Island' },
  { label: 'Botswana' },
  { label: 'Belarus' },
  { label: 'Belize' },
  { label: 'Canada' },
  { label: 'Cocos (Keeling) Islands' },
  { label: 'Congo, Democratic Republic of the' },
  { label: 'Central African Republic' },
  { label: 'Congo, Republic of the' },
  { label: 'Switzerland' },
  { label: "Cote d'Ivoire" },
  { label: 'Cook Islands' },
  { label: 'Chile' },
  { label: 'Cameroon' },
  { label: 'China' },
  { label: 'Colombia' },
  { label: 'Costa Rica' },
  { label: 'Cuba' },
  { label: 'Cape Verde' },
  { label: 'Curacao' },
  { label: 'Christmas Island' },
  { label: 'Cyprus' },
  { label: 'Czech Republic' },
  { label: 'Germany' },
  { label: 'Djibouti' },
  { label: 'Denmark' },
  { label: 'Dominica' },
  { label: 'Dominican Republic' },
  { label: 'Algeria' },
  { label: 'Ecuador' },
  { label: 'Estonia' },
  { label: 'Egypt' },
  { label: 'Western Sahara' },
  { label: 'Eritrea' },
  { label: 'Spain' },
  { label: 'Ethiopia' },
  { label: 'Finland' },
  { label: 'Fiji' },
  { label: 'Falkland Islands (Malvinas)' },
  { label: 'Micronesia, Federated States of' },
  { label: 'Faroe Islands' },
  { label: 'France' },
  { label: 'Gabon' },
  { label: 'United Kingdom' },
  { label: 'Grenada' },
  { label: 'Georgia' },
  { label: 'French Guiana' },
  { label: 'Guernsey' },
  { label: 'Ghana' },
  { label: 'Gibraltar' },
  { label: 'Greenland' },
  { label: 'Gambia' },
  { label: 'Guinea' },
  { label: 'Guadeloupe' },
  { label: 'Equatorial Guinea' },
  { label: 'Greece' },
  { label: 'South Georgia and the South Sandwich Islands' },
  { label: 'Guatemala' },
  { label: 'Guam' },
  { label: 'Guinea-Bissau' },
  { label: 'Guyana' },
  { label: 'Hong Kong' },
  { label: 'Heard Island and McDonald Islands' },
  { label: 'Honduras' },
  { label: 'Croatia' },
  { label: 'Haiti' },
  { label: 'Hungary' },
  { label: 'Indonesia' },
  { label: 'Ireland' },
  { label: 'Israel' },
  { label: 'Isle of Man' },
  { label: 'India' },
  { label: 'British Indian Ocean Territory' },
  { label: 'Iraq' },
  { label: 'Iran, Islamic Republic of' },
  { label: 'Iceland' },
  { label: 'Italy' },
  { label: 'Jersey' },
  { label: 'Jamaica' },
  { label: 'Jordan' },
  { label: 'Japan' },
  { label: 'Kenya' },
  { label: 'Kyrgyzstan' },
  { label: 'Cambodia' },
  { label: 'Kiribati' },
  { label: 'Comoros' },
  { label: 'Saint Kitts and Nevis' },
  { label: "Korea, Democratic People's Republic of" },
  { label: 'Korea, Republic of' },
  { label: 'Kuwait' },
  { label: 'Cayman Islands' },
  { label: 'Kazakhstan' },
  { label: "Lao People's Democratic Republic" },
  { label: 'Lebanon' },
  { label: 'Saint Lucia' },
  { label: 'Liechtenstein' },
  { label: 'Sri Lanka' },
  { label: 'Liberia' },
  { label: 'Lesotho' },
  { label: 'Lithuania' },
  { label: 'Luxembourg' },
  { label: 'Latvia' },
  { label: 'Libya' },
  { label: 'Morocco' },
  { label: 'Monaco' },
  { label: 'Moldova, Republic of' },
  { label: 'Montenegro' },
  { label: 'Saint Martin (French part)' },
  { label: 'Madagascar' },
  { label: 'Marshall Islands' },
  { label: 'Macedonia, the Former Yugoslav Republic of' },
  { label: 'Mali' },
  { label: 'Myanmar' },
  { label: 'Mongolia' },
  { label: 'Macao' },
  { label: 'Northern Mariana Islands' },
  { label: 'Martinique' },
  { label: 'Mauritania' },
  { label: 'Montserrat' },
  { label: 'Malta' },
  { label: 'Mauritius' },
  { label: 'Maldives' },
  { label: 'Malawi' },
  { label: 'Mexico' },
  { label: 'Malaysia' },
  { label: 'Mozambique' },
  { label: 'Namibia' },
  { label: 'New Caledonia' },
  { label: 'Niger' },
  { label: 'Norfolk Island' },
  { label: 'Nigeria' },
  { label: 'Nicaragua' },
  { label: 'Netherlands' },
  { label: 'Norway' },
  { label: 'Nepal' },
  { label: 'Nauru' },
  { label: 'Niue' },
  { label: 'New Zealand' },
  { label: 'Oman' },
  { label: 'Panama' },
  { label: 'Peru' },
  { label: 'French Polynesia' },
  { label: 'Papua New Guinea' },
  { label: 'Philippines' },
  { label: 'Pakistan' },
  { label: 'Poland' },
  { label: 'Saint Pierre and Miquelon' },
  { label: 'Pitcairn' },
  { label: 'Puerto Rico' },
  { label: 'Palestine, State of' },
  { label: 'Portugal' },
  { label: 'Palau' },
  { label: 'Paraguay' },
  { label: 'Qatar' },
  { label: 'Reunion' },
  { label: 'Romania' },
  { label: 'Serbia' },
  { label: 'Russian Federation' },
  { label: 'Rwanda' },
  { label: 'Saudi Arabia' },
  { label: 'Solomon Islands' },
  { label: 'Seychelles' },
  { label: 'Sudan' },
  { label: 'Sweden' },
  { label: 'Singapore' },
  { label: 'Saint Helena' },
  { label: 'Slovenia' },
  { label: 'Svalbard and Jan Mayen' },
  { label: 'Slovakia' },
  { label: 'Sierra Leone' },
  { label: 'San Marino' },
  { label: 'Senegal' },
  { label: 'Somalia' },
  { label: 'Suriname' },
  { label: 'South Sudan' },
  { label: 'Sao Tome and Principe' },
  { label: 'El Salvador' },
  { label: 'Sint Maarten (Dutch part)' },
  { label: 'Syrian Arab Republic' },
  { label: 'Swaziland' },
  { label: 'Turks and Caicos Islands' },
  { label: 'Chad' },
  { label: 'French Southern Territories' },
  { label: 'Togo' },
  { label: 'Thailand' },
  { label: 'Tajikistan' },
  { label: 'Tokelau' },
  { label: 'Timor-Leste' },
  { label: 'Turkmenistan' },
  { label: 'Tunisia' },
  { label: 'Tonga' },
  { label: 'Turkey' },
  { label: 'Trinidad and Tobago' },
  { label: 'Tuvalu' },
  { label: 'Taiwan, Republic of China' },
  { label: 'United Republic of Tanzania' },
  { label: 'Ukraine' },
  { label: 'Uganda' },
  { label: 'United States' },
  { label: 'Uruguay' },
  { label: 'Uzbekistan' },
  { label: 'Holy See (Vatican City State)' },
  { label: 'Saint Vincent and the Grenadines' },
  { label: 'Venezuela' },
  { label: 'British Virgin Islands' },
  { label: 'US Virgin Islands' },
  { label: 'Vietnam' },
  { label: 'Vanuatu' },
  { label: 'Wallis and Futuna' },
  { label: 'Samoa' },
  { label: 'Kosovo' },
  { label: 'Yemen' },
  { label: 'Mayotte' },
  { label: 'South Africa' },
  { label: 'Zambia' },
  { label: 'Zimbabwe' },
];

export const states = {
  India: [
    { label: 'Andaman & Nicobar Islands' },
    { label: 'Andhra Pradesh' },
    { label: 'Arunachal Pradesh' },
    { label: 'Assam' },
    { label: 'Bihar' },
    { label: 'Chandigarh' },
    { label: 'Chhattisgarh' },
    { label: 'Dadra & Nagar Haveli' },
    { label: 'Daman & Diu' },
    { label: 'Delhi' },
    { label: 'Goa' },
    { label: 'Gujarat' },
    { label: 'Haryana' },
    { label: 'Himachal Pradesh' },
    { label: 'Jammu & Kashmir' },
    { label: 'Jharkhand' },
    { label: 'Karnataka' },
    { label: 'Kerala' },
    { label: 'Lakshyadeep' },
    { label: 'Madhya Pradesh' },
    { label: 'Maharashtra' },
    { label: 'Manipur' },
    { label: 'Meghalaya' },
    { label: 'Mizoram' },
    { label: 'Nagaland' },
    { label: 'Orissa' },
    { label: 'Puducherry' },
    { label: 'Punjab' },
    { label: 'Rajasthan' },
    { label: 'Sikkim' },
    { label: 'Tamil Nadu' },
    { label: 'Telangana' },
    { label: 'Tripura' },
    { label: 'Uttarakhand' },
    { label: 'Uttar Pradesh' },
    { label: 'West Bengal' },
  ],
  ['United States']: [
    { label: 'Arizona' },
    { label: 'California' },
    { label: 'Florida' },
    { label: 'Georgia' },
    { label: 'Kansas' },
    { label: 'Louisiana' },
    { label: 'Michigan' },
    { label: 'New York' },
    { label: 'Texas' },
    { label: 'Washington' },
  ],
};

export const cities = {
  ['Andaman & Nicobar Islands']: [
    { label: 'Bakultala ' },
    { label: 'Car Nicobar' },
    { label: 'Kamorta' },
    { label: 'Port Blair' },
    { label: 'Rangat' },
  ],
  ['Andhra Pradesh']: [
    { label: 'Achanta ' },
    { label: 'Adoni' },
    { label: 'Allur' },
    { label: 'Amalapuram' },
    { label: 'Guntur' },
  ],
  ['Arunachal Pradesh']: [
    { label: 'Along' },
    { label: 'Basar' },
    { label: 'Basar' },
    { label: 'Hawai ' },
    { label: 'Itanagar' },
  ],
  Assam: [
    { label: 'Anand Nagar' },
    { label: 'Badarpur' },
    { label: 'Dispur' },
    { label: 'Guwahati ' },
    { label: 'Tezpur' },
  ],
  Bihar: [
    { label: 'Bahadurpur' },
    { label: 'Barauli ' },
    { label: 'Gaya' },
    { label: 'Patna ' },
    { label: 'Shahpur' },
  ],
  Chandigarh: [
    { label: 'Chandigarh' },
    { label: 'Mohali ' },
    { label: 'Panchkula' },
  ],
  Chhattisgarh: [
    { label: 'Aamdi' },
    { label: 'Balrampur ' },
    { label: 'Devkar' },
    { label: 'Govindapur ' },
    { label: 'Raipur' },
  ],
  ['Dadra & Nagar Haveli']: [
    { label: 'Alok City' },
    { label: 'Amli ' },
    { label: 'Dungra' },
    { label: 'Naroli ' },
    { label: 'Surangi' },
  ],
  ['Daman & Diu']: [
    { label: 'Dadhel' },
    { label: 'Daman ' },
    { label: 'Diu' },
    { label: 'Ghoghla' },
    { label: 'Kachigam' },
  ],
  Delhi: [
    { label: 'Ali Pur ' },
    { label: 'Gharoli' },
    { label: 'Firozabad' },
    { label: 'New Delhi' },
    { label: 'Shahjehabanad ' },
  ],
  Goa: [
    { label: 'Aldona' },
    { label: 'Borim' },
    { label: 'Old Goa' },
    { label: 'Panaji ' },
    { label: 'Siolim' },
  ],
  Gujarat: [
    { label: 'Ahmedabad' },
    { label: 'Babra' },
    { label: 'Dwarka' },
    { label: 'Gandhinagar ' },
    { label: 'Himmatnagar' },
  ],
  Haryana: [
    { label: 'Ambala' },
    { label: 'Faridabad' },
    { label: 'Gurgaon' },
    { label: 'Hisar ' },
    { label: 'Panipat' },
  ],
  ['Himachal Pradesh']: [
    { label: 'Bilaspur' },
    { label: 'Dharmsala' },
    { label: 'Kasol ' },
    { label: 'Manali' },
    { label: 'Shimla' },
  ],
  ['Jammu & Kashmir']: [
    { label: 'Anantnag' },
    { label: 'Jammu' },
    { label: 'Hiranagar' },
    { label: 'Leh' },
    { label: 'Srinagar' },
  ],
  Jharkhand: [
    { label: 'Bishrampur' },
    { label: 'Mandu' },
    { label: 'Ranchi' },
    { label: 'Shahpur' },
  ],
  Karnataka: [
    { label: 'Addur' },
    { label: 'Bengaluru' },
    { label: 'Chitapur' },
    { label: 'Krishnaraja Sagara' },
    { label: 'Somvarpet' },
  ],
  Kerala: [
    { label: 'Adoor' },
    { label: 'Balusseri' },
    { label: 'Haripad' },
    { label: 'Kattur' },
    { label: 'Pallikkal' },
  ],
  Lakshyadeep: [
    { label: 'Agatti' },
    { label: 'Amini' },
    { label: 'Kavaratti' },
    { label: 'Minicoy' },
  ],
  ['Madhya Pradesh']: [
    { label: 'Alampur' },
    { label: 'Bareli' },
    { label: 'Chitrakoot' },
    { label: 'Jabalpur' },
    { label: 'Sultanpur' },
  ],
  Maharashtra: [
    { label: 'Kolhapur' },
    { label: 'Mumbai' },
    { label: 'Nagpur' },
    { label: 'Nashik' },
    { label: 'Pune' },
  ],
  Manipur: [
    { label: 'Andro' },
    { label: 'Imphal' },
    { label: 'Lilong' },
    { label: 'Moirang' },
    { label: 'Senapati' },
  ],
  Meghalaya: [
    { label: 'Baghmara' },
    { label: 'Cherrapunjee' },
    { label: 'Shilomg' },
    { label: 'Umroi' },
    { label: 'Williamnagar' },
  ],
  Mizoram: [
    { label: 'Aizawl' },
    { label: 'Bairabi' },
    { label: 'Champhai' },
    { label: 'Sairang' },
    { label: 'Tlabung' },
  ],
  Nagaland: [
    { label: 'Dimapur' },
    { label: 'Longleng' },
    { label: 'Mon Town' },
    { label: 'Peren' },
    { label: 'Wokha' },
  ],
  Orissa: [
    { label: 'Anandpur' },
    { label: 'Balakati' },
    { label: 'Gopalpur' },
    { label: 'Mohana' },
    { label: 'Puri' },
  ],
  Puducherry: [
    { label: 'Karaikal' },
    { label: 'Mahe' },
    { label: 'Ozhukarai' },
    { label: 'Pondicherry' },
    { label: 'Yanam' },
  ],
  Punjab: [
    { label: 'Adampur' },
    { label: 'Dharamkot' },
    { label: 'Firozpur' },
    { label: 'Patiala' },
    { label: 'Shahkot' },
  ],
  Rajasthan: [
    { label: 'Aligarh' },
    { label: 'Bikaner' },
    { label: 'Jaipur' },
    { label: 'Jodhpur' },
    { label: 'Kota' },
  ],
  Sikkim: [
    { label: 'Gangtok' },
    { label: 'Mangan' },
    { label: 'Pelling' },
    { label: 'Rangpo' },
    { label: 'Singtam' },
  ],
  ['Tamil Nadu']: [
    { label: 'Chennai' },
    { label: 'Coimbatore' },
    { label: 'Madurai' },
    { label: 'Vellore' },
    { label: 'Tiruchirappalli' },
  ],
  Telangana: [
    { label: 'Ameenapur' },
    { label: 'Hyderabad' },
    { label: 'Nizamabad' },
    { label: 'Shamshabad' },
    { label: 'Warangal' },
  ],
  Tripura: [
    { label: 'Agartala' },
    { label: 'Belonia' },
    { label: 'Dharmanagar' },
    { label: 'Khowai' },
    { label: 'Sonamura' },
  ],
  Uttarakhand: [
    { label: 'Dehradun' },
    { label: 'Haridwar' },
    { label: 'Rishikesh' },
    { label: 'Nainital' },
    { label: 'Haldwani' },
  ],
  ['Uttar Pradesh']: [
    { label: 'Agra' },
    { label: 'Kanpur' },
    { label: 'Lucknow' },
    { label: 'Meerut' },
    { label: 'Varanasi' },
  ],
  ['West Bengal']: [
    { label: 'Durgapur' },
    { label: 'Howrah' },
    { label: 'Kolkata' },
    { label: 'Murshidabad' },
    { label: 'West Medinipur' },
  ],
  Arizona: [
    { label: 'Flagstaff' },
    { label: 'Mesa' },
    { label: 'Scottsdale' },
    { label: 'Tempe' },
    { label: 'Tucson' },
  ],
  California: [
    { label: 'Los Angeles' },
    { label: 'Oakland' },
    { label: 'Sacramento' },
    { label: 'San Diego' },
    { label: 'San Francisco' },
  ],
  Florida: [
    { label: 'Jacksonville' },
    { label: 'Miami' },
    { label: 'Orlando' },
    { label: 'Pensacola' },
    { label: 'Tampa' },
  ],
  Georgia: [
    { label: 'Atlanta' },
    { label: 'Augusta-Richmond County' },
    { label: 'Columbus' },
    { label: 'Savannah' },
    { label: 'Sandy Springs' },
  ],
  Kansas: [
    { label: 'Kansas City' },
    { label: 'Olathe' },
    { label: 'Overland Park' },
    { label: 'Westwood' },
    { label: 'Wichita' },
  ],
  Louisiana: [
    { label: 'Baton Rouge' },
    { label: 'Lafayette' },
    { label: 'Metairie' },
    { label: 'New Orleans' },
    { label: 'Shreveport' },
  ],
  Michigan: [
    { label: 'Detroit' },
    { label: 'Grand Rapids' },
    { label: 'Lansing' },
    { label: 'Sterling Heights' },
    { label: 'Warren' },
  ],
  ['New York']: [
    { label: 'Brooklyn' },
    { label: 'Manhattan' },
    { label: 'Queens' },
    { label: 'Staten Island' },
    { label: 'The Bronx' },
  ],
  Texas: [
    { label: 'Austin' },
    { label: 'Dallas' },
    { label: 'Houstan' },
    { label: 'McKinney' },
    { label: 'San Antonio' },
  ],
  Washington: [
    { label: 'Bellingham' },
    { label: 'Olympia' },
    { label: 'Port Angeles' },
    { label: 'Seattle' },
    { label: 'Vancouver' },
  ],
};
